# Generated by Django 3.2.5 on 2022-09-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField()),
                ('score', models.FloatField()),
                ('horse_number', models.IntegerField()),
                ('favorite', models.IntegerField()),
                ('horse_name', models.CharField(max_length=100)),
                ('jockey', models.CharField(max_length=100)),
            ],
        ),
    ]
